---
name: Reusable CI

# --------------------------------------------------------------------------
# This workflow only runs when explicitly called by another workflow.
# --------------------------------------------------------------------------
on:
  workflow_call:

# This workflow is passive so ensure the minimal permissions even if the
# inherited token is more lenient.
permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  megalinter:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        run: npm install @commitlint/cli @commitlint/config-conventional

      - name: Validate PR Title
        if: ${{ github.event.pull_request.title != '' }}
        env:
          PR_TITLE: "${{ github.event.pull_request.title }}"
        run: echo "$PR_TITLE" | npx commitlint --config commitlint.config.js

      - name: Run MegaLinter
        id: megalinter
        uses: oxsecurity/megalinter@42bb470545e359597e7f12156947c436e4e3fb9a # v9.3.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          GITHUB_COMMENT_REPORTER: false
          GOTOOLCHAIN: auto
